/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT C6414_2012_Full.cdb */

/*  Include Header File  */
#include "C6414_2012_Fullcfg.h"


#ifdef __cplusplus
#pragma CODE_SECTION(".text:CSL_cfgInit")
#else
#pragma CODE_SECTION(CSL_cfgInit,".text:CSL_cfgInit")
#endif


#ifdef __cplusplus
#pragma FUNC_EXT_CALLED()
#else
#pragma FUNC_EXT_CALLED(CSL_cfgInit)
#endif

/*  Config Structures */
EDMA_Config edmaCfg_FingerVein = {
    0x20A00005,        /*  Option  */
    0x80000000,        /*  Source Address - Numeric   */
    0x0153005A,        /*  Transfer Counter - Numeric  */
    0x80000000,        /*  Destination Address - Numeric   */
    0x00000000,        /*  Index register - Numeric  */
    0x00000000         /*  Element Count Reload and Link Address  */
};

EDMA_Config edmaCfg_FingerPrint = {
    0x20A00005,        /*  Option  */
    0x80000000,        /*  Source Address - Numeric   */
    0x01D5012C,        /*  Transfer Counter - Numeric  */
    0x80000000,        /*  Destination Address - Numeric   */
    0x00000000,        /*  Index register - Numeric  */
    0x00000000         /*  Element Count Reload and Link Address  */
};

EMIFA_Config MyEmifaConfig = {
    0x000120BC,        /*  Global Control Reg. (GBLCTL)   */
    0xFFFFFFD3,        /*  CE0 Space Control Reg. (CECTL0)   */
    0xFFFFFFC3,        /*  CE1 Space Control Reg. (CECTL1)   */
    0x22A28A22,        /*  CE2 Space Control Reg. (CECTL2)   */
    0x22A28A22,        /*  CE3 Space Control Reg. (CECTL3)   */
    0x47228000,        /*  SDRAM Control Reg.(SDCTL)   */
    0x005DC753,        /*  SDRAM Timing Reg.(SDTIM)   */
    0x0007052A,        /*  SDRAM Extended Reg.(SDEXT)   */
    0x00000002,        /*  CE0 Space Secondary Control Reg. (CESEC0)  */
    0x00000002,        /*  CE1 Space Secondary Control Reg. (CESEC1)  */
    0x00000002,        /*  CE2 Space Secondary Control Reg. (CESEC2)  */
    0x00000002         /*  CE3 Space Secondary Control Reg. (CESEC3)  */
};

EMIFB_Config MyEmifbConfig = {
    0x0001203C,        /*  Global Control Reg. (GBLCTL)   */
    0xFFFFFF13,        /*  CE0 Space Control Reg. (CECTL0)   */
    0xFFFFFF13,        /*  CE1 Space Control Reg. (CECTL1)   */
    0xFFFFFF13,        /*  CE2 Space Control Reg. (CECTL2)   */
    0xFFFFFF13,        /*  CE3 Space Control Reg. (CECTL3)   */
    0x0348F000,        /*  SDRAM Control Reg.(SDCTL)   */
    0x005DC5DC,        /*  SDRAM Timing Reg.(SDTIM)   */
    0x00175F3F,        /*  SDRAM Extended Reg.(SDEXT)   */
    0x00000006,        /*  CE0 Space Secondary Control Reg. (CESEC0)  */
    0x00000002,        /*  CE1 Space Secondary Control Reg. (CESEC1)  */
    0x00000002,        /*  CE2 Space Secondary Control Reg. (CESEC2)  */
    0x00000002         /*  CE3 Space Secondary Control Reg. (CESEC3)  */
};

/*  Handles  */
EDMA_Handle hEdmaCha5;
EDMA_Handle hEdmaCha7;

/*
 *  ======== CSL_cfgInit() ========  
 */
void CSL_cfgInit()
{
    hEdmaCha5 = EDMA_open(EDMA_CHA_EXTINT5, EDMA_OPEN_RESET);
    hEdmaCha7 = EDMA_open(EDMA_CHA_EXTINT7, EDMA_OPEN_RESET);
    EDMA_config(hEdmaCha5, &edmaCfg_FingerVein);
    EDMA_enableChannel(hEdmaCha5);
    EDMA_config(hEdmaCha7, &edmaCfg_FingerPrint);
    EDMA_enableChannel(hEdmaCha7);
    EMIFA_config(&MyEmifaConfig);
    EMIFB_config(&MyEmifbConfig);
}
